import type { Metadata } from "next";

import {Space_Grotesk} from "next/font/google"
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"




//font
const spaceGrotesk=Space_Grotesk({subsets:["latin"]})


export const metadata: Metadata = {
  title: "Sok Tityapong",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: "/pong.png",
        href: "/pong.png",
        sizes: "any",
        type: "image/png",
      },
    ],
  },

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
       <body className={spaceGrotesk.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </body>
    </html>
  );
}
